name: Terraform EC2 Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_VERSION: "1.15"
  AWS_REGION: "eu-west-2"
  TF_DIR: "ec2/infra/envs/prod"
  PLAN_ROLE:   "arn:aws:iam::707421297413:role/github-actions-terraform-plan"
  APPLY_ROLE:  "arn:aws:iam::707421297413:role/github-actions-terraform-apply"

jobs:
  validate:
    name: Validate & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform version
        run: terraform --version

      - name: Terraform format check
        run: terraform fmt -check -recursive ec2/

      - name: Validate
        run: terraform validate
        working-directory: ${{ env.TFDIR }}